name: "flight_fares"
version: "1.0.0"
config-version: 2

profile: "flight_fares"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  flight_fares:
    staging:
      +schema: "{{ env_var('REDSHIFT_SCHEMA_STAGING', 'staging') }}"
      +materialized: view
    marts:
      +schema: "{{ env_var('REDSHIFT_SCHEMA_MARTS', 'marts') }}"
      +materialized: table
